
name: Deploy GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 2,4"  # Tuesdays and Thursdays at 10 AM New York time
  push:
    branches: [ "main" ]  # Trigger on pushes to main branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'  # Specify the required Ruby version
          bundler-cache: true  # Cache dependencies

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build  # Modify if using a different static site generator

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3  # Upload generated site for deployment

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy site
        uses: actions/deploy-pages@v4

