name: Sync Google Sheet to YAML

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"  # 9 AM New York time

jobs:
  sync-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: scripts

      - name: Prepare credentials
        run: echo "${{ secrets.GSHEET_CRED }}" > service_creds.json
        working-directory: scripts

      - name: Run sync script
        run: python sync_events.py
        working-directory: scripts

      - name: Clean up credentials
        run: rm service_creds.json
        working-directory: scripts

      - name: Commit & push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/events.yml
          git diff --cached --quiet || git commit -m "Auto-sync events from Google Sheets"
          git push